### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by Kekun** [alexis-puska/lr-multi-bomberman#3]
When running the core in RetroArch on Linux (Fedora 25), the application instantaneously crashes, here is the backtrace:
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
Bomberman::copySurfaceToBackRenderer (this=this@entry=0x42c8a70, src=0x0, 
    dest=dest@entry=0x42c8b10, x=x@entry=0, y=y@entry=0) at src/bomberman/Bomberman.cpp:166
166		dstRect.h = src->h;
(gdb) bt
#0  Bomberman::copySurfaceToBackRenderer (this=this@entry=0x42c8a70, src=0x0, 
    dest=dest@entry=0x42c8b10, x=x@entry=0, y=y@entry=0) at src/bomberman/Bomberman.cpp:166
#1  0x00007fffed4a03fd in Bomberman::Bomberman (this=0x42c8a70, 
    vout_bufLibretro=<optimized out>) at src/bomberman/Bomberman.cpp:24
#2  0x00007fffed4a1f81 in newBomberman (vout_buf=0x42c8970) at src/bomberman/MyWrapper.cpp:6
#3  0x00007fffed4a0158 in retro_init () at src/libretro/libretro.c:443
#4  0x000000000041324a in core_init () at core_impl.c:330
#5  0x000000000041982f in command_event_init_core (data=0x7db7e4 <current_core_type>)
    at command.c:1374
#6  command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT, 
    data=data@entry=0x7db7e4 <current_core_type>) at command.c:2251
#7  0x0000000000415e5f in retroarch_main_init (argc=3, argv=argv@entry=0x7fffffffdb08)
    at retroarch.c:1361
#8  0x0000000000423f97 in content_load (info=0x7fffffffd9f0) at tasks/task_content.c:979
#9  task_load_content (content_info=content_info@entry=0x7fffffffd9f0, 
    launched_from_menu=launched_from_menu@entry=false, mode=CONTENT_MODE_LOAD_FROM_CLI)
    at tasks/task_content.c:1666
#10 0x0000000000425c69 in task_push_content_load_default (core_path=core_path@entry=0x0, 
    fullpath=fullpath@entry=0x0, content_info=content_info@entry=0x7fffffffd9f0, 
    type=type@entry=CORE_TYPE_PLAIN, mode=mode@entry=CONTENT_MODE_LOAD_FROM_CLI, 
    cb=cb@entry=0x0, user_data=0x0) at tasks/task_content.c:2009
#11 0x00000000004123f2 in rarch_main (argc=3, argv=0x7fffffffdb08, data=0x0)
    at frontend/frontend.c:104
#12 0x00007ffff3ef3401 in __libc_start_main (main=0x40fa30 <main>, argc=3, 
    argv=0x7fffffffdb08, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdaf8) at ../csu/libc-start.c:289
#13 0x000000000040fa69 in _start ()
(gdb) 
```

**Comment by alexis-puska** [comment]
Bug fixe, all resources files is now compile in code and include in the library. you can move the library on your hard file to use it without move the resource folder
